# Generated by Django 5.2.6 on 2025-09-26 13:57

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_catagory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='uploads/default.png', null=True, upload_to=shop.models.getFileName),
        ),
    ]
